import React, { useState } from 'react';
import { 
  X, 
  FileText, 
  Scale, 
  ShieldCheck, 
  AlertTriangle, 
  Code2, 
  Copy, 
  Check, 
  ExternalLink 
} from 'lucide-react';
import { openExternalLink } from '../../utils/openExternal';

interface LicenseModalProps {
  isOpen: boolean;
  onClose: () => void;
  initialTab?: 'eula' | 'cleanroom' | 'safety' | 'opensource';
}

type TabKey = 'eula' | 'cleanroom' | 'safety' | 'opensource';

const FULL_LICENSE_TEXT = `WILDCAT STUDIO — END USER LICENSE AGREEMENT & LEGAL NOTICES
Version 1.0.0 • Copyright (c) 2026 Daniel Cook / Wildcat Studio. All rights reserved.

1. PROPRIETARY FREEWARE LICENSE GRANT
Wildcat Studio ("the Software") is proprietary software provided free of charge ("Freeware") for personal, hobbyist, educational, and professional gunsmithing / toolmaking cartridge design and calculation.

Under this license, you are granted a non-exclusive, non-transferable, revocable license to:
- Install and execute the official binary distributions on any compatible computer system.
- Create, modify, save, and export cartridge dimensional specifications (.wildcat, .wcs).
- Generate and print engineering blueprints, 2D vector CAD drawings, and chamber reamer specifications for reamer manufacturers (JGS, PTG, Manson).
- Utilize the mathematical solvers for personal ballistic experimentation, educational research, and custom chamber design.

2. RESTRICTIONS & CONFIDENTIAL SOURCE CODE
The source code, mathematical algorithms, native numerical integrators, and internal data structures are the exclusive intellectual property of Daniel Cook.
You may NOT:
- Decompile, reverse engineer, disassemble, or attempt to derive the source code from official compiled binaries.
- Modify, adapt, translate, or create derivative works of the executable or application bundle.
- Sell, rent, lease, sublicense, or distribute modified copies of the Software for commercial gain.
- Publicly redistribute repackaged binary releases without explicit prior written authorization. Official distributions are hosted exclusively via https://armstrader.store/wildcat-studio and authorized GitHub repositories.

3. CLEANROOM IMPLEMENTATION & MATHEMATICAL ATTRIBUTION
All mathematical and ballistic calculations implemented in Wildcat Studio are independent, cleanroom derivations:
- Volumetric Integration: Liquid grain water capacity (gr H2O) is calculated via 1,000-slice Simpson composite numerical integration of the interior cartridge solid of revolution.
- Gyroscopic Stability: Projectile stability calculations implement the Don Miller twist rule (Sg) with standard temperature and barometric atmospheric pressure corrections.
- Spin Drift: Aerodynamic drift formulations implement Bryan Litz empirical point-mass projectile deflection equations.
- Dimensional Data: Reference cartridge and chamber envelopes are derived from public domain technical drawings published by SAAMI (Sporting Arms and Ammunition Manufacturers' Institute) and C.I.P. (Commission Internationale Permanente).

4. RELOADING & CHAMBERING SAFETY DISCLAIMER (CRITICAL)
ALL OUTPUT, DIMENSIONS, POWDER CAPACITY FIGURES, PREDICTED VELOCITIES, AND PEAK PRESSURE ESTIMATES GENERATED BY WILDCAT STUDIO ARE THEORETICAL MATHEMATICAL APPROXIMATIONS INTENDED SOLELY FOR DRAFTING, TOOLROOM REFERENCE, AND GENERAL BALLISTIC COMPARISON.

WARNING:
- Handloading ammunition and wildcat chamber cutting carry inherent physical risks. Actual chamber pressures, velocities, and powder combustion dynamics are heavily influenced by propellant lot variations, primer hardness, ambient temperature, barrel twist rate, chamber throat dimensions, and bore finish.
- NEVER cut a rifle chamber or assemble live ammunition relying solely on calculated outputs.
- ALWAYS verify finished chambers using calibrated precision GO / NO-GO headspace gauges manufactured by qualified toolmakers.
- ALWAYS cross-reference published load manuals (Hodgdon, Alliant, Vihtavuori, Hornady, Sierra) and begin load development at least 10% below any estimated maximum charge.
- The author and contributors accept ZERO liability for personal injury, property damage, firearm destruction, or regulatory non-compliance arising from the use of this software.

5. THIRD-PARTY & OPEN SOURCE ACKNOWLEDGEMENTS
Wildcat Studio utilizes open source libraries licensed under permissive terms:
- Tauri (MIT / Apache-2.0) — Rust native desktop application framework
- React & React-DOM (MIT) — Component user interface architecture
- Three.js (MIT) — WebGL 3D solid lathe and cylinder rendering
- Lucide Icons (ISC) — Clean vector interface typography and iconography
- Vite (MIT) — Application bundler and modern build system

Official Distribution & Ecosystem Portal:
https://armstrader.store/wildcat-studio
`;

export const LicenseModal: React.FC<LicenseModalProps> = ({ 
  isOpen, 
  onClose,
  initialTab = 'eula' 
}) => {
  const [activeTab, setActiveTab] = useState<TabKey>(initialTab);
  const [copied, setCopied] = useState<boolean>(false);

  if (!isOpen) return null;

  const handleCopy = () => {
    navigator.clipboard.writeText(FULL_LICENSE_TEXT).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2200);
    });
  };

  return (
    <div 
      style={{
        position: 'fixed',
        inset: 0,
        background: 'rgba(5, 8, 14, 0.82)',
        WebkitBackdropFilter: 'blur(12px)',
        backdropFilter: 'blur(12px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 1000,
        padding: '16px'
      }}
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div 
        onClick={(e) => e.stopPropagation()}
        style={{
          background: '#0a0e17',
          border: '1px solid rgba(0, 210, 255, 0.35)',
          borderRadius: '10px',
          width: '740px',
          maxWidth: '94vw',
          height: '680px',
          maxHeight: '90vh',
          display: 'flex',
          flexDirection: 'column',
          boxShadow: '0 24px 60px rgba(0, 0, 0, 0.9), 0 0 30px rgba(0, 210, 255, 0.15)',
          position: 'relative',
          overflow: 'hidden'
        }}
      >
        {/* HEADER */}
        <div style={{
          padding: '18px 24px',
          borderBottom: '1px solid rgba(255, 255, 255, 0.08)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          background: 'rgba(255, 255, 255, 0.02)',
          flexShrink: 0
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <div style={{
              width: '36px',
              height: '36px',
              borderRadius: '8px',
              background: 'rgba(0, 210, 255, 0.12)',
              border: '1px solid rgba(0, 210, 255, 0.3)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center'
            }}>
              <Scale size={20} color="var(--cad-cyan)" />
            </div>
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <h3 style={{ fontSize: '16px', fontWeight: 800, color: '#fff', margin: 0 }}>
                  Software License & Legal Terms
                </h3>
                <span style={{
                  fontSize: '10px',
                  fontWeight: 700,
                  textTransform: 'uppercase',
                  letterSpacing: '0.5px',
                  padding: '2px 6px',
                  borderRadius: '4px',
                  background: 'rgba(0, 210, 255, 0.15)',
                  color: 'var(--cad-cyan)',
                  border: '1px solid rgba(0, 210, 255, 0.3)'
                }}>
                  Proprietary Freeware
                </span>
              </div>
              <p style={{ fontSize: '11px', color: 'var(--text-muted)', margin: '2px 0 0 0' }}>
                Wildcat Studio v1.0.0 • Cleanroom Precision Ballistics & Cartridge CAD
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            style={{
              background: 'transparent',
              border: 'none',
              color: 'var(--text-muted)',
              cursor: 'pointer',
              padding: '6px',
              borderRadius: '6px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              transition: 'all 0.15s'
            }}
            title="Close dialog (Esc)"
          >
            <X size={18} />
          </button>
        </div>

        {/* TAB NAVIGATION */}
        <div style={{
          display: 'flex',
          borderBottom: '1px solid rgba(255, 255, 255, 0.08)',
          background: 'rgba(0, 0, 0, 0.25)',
          padding: '0 20px',
          gap: '4px',
          flexShrink: 0
        }}>
          {[
            { key: 'eula', label: 'End User License (EULA)', icon: FileText },
            { key: 'cleanroom', label: 'Cleanroom & Algorithms', icon: Code2 },
            { key: 'safety', label: 'Safety & Liability Advisory', icon: AlertTriangle },
            { key: 'opensource', label: 'Open Source Notices', icon: ShieldCheck },
          ].map((tab) => {
            const Icon = tab.icon;
            const isActive = activeTab === tab.key;
            return (
              <button
                key={tab.key}
                onClick={() => setActiveTab(tab.key as TabKey)}
                style={{
                  background: 'transparent',
                  border: 'none',
                  borderBottom: isActive ? '2px solid var(--cad-cyan)' : '2px solid transparent',
                  color: isActive ? '#fff' : 'var(--text-secondary)',
                  padding: '10px 14px',
                  fontSize: '12px',
                  fontWeight: isActive ? 700 : 500,
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '6px',
                  transition: 'all 0.15s'
                }}
              >
                <Icon size={14} color={isActive ? "var(--cad-cyan)" : "var(--text-muted)"} />
                <span>{tab.label}</span>
              </button>
            );
          })}
        </div>

        {/* SCROLLABLE BODY */}
        <div style={{
          flex: 1,
          overflowY: 'auto',
          padding: '22px 24px',
          fontSize: '12px',
          lineHeight: 1.65,
          color: 'var(--text-secondary)',
          display: 'flex',
          flexDirection: 'column',
          gap: '16px',
          minHeight: 0
        }}>
          {activeTab === 'eula' && (
            <>
              <div style={{
                background: 'rgba(0, 210, 255, 0.06)',
                border: '1px solid rgba(0, 210, 255, 0.2)',
                borderRadius: '6px',
                padding: '12px 14px',
                color: '#e2e8f0'
              }}>
                <strong style={{ color: 'var(--cad-cyan)', display: 'block', marginBottom: '4px' }}>
                  Proprietary Freeware Grant
                </strong>
                Wildcat Studio is made freely available for individual gunsmiths, toolmakers, cartridge wildcatters, and precision shooting enthusiasts. You are free to design, blueprint, and machine chambers without royalties or licensing fees.
              </div>

              <div>
                <h4 style={{ color: '#fff', fontSize: '13px', fontWeight: 700, margin: '0 0 6px 0' }}>
                  1. Permitted Uses
                </h4>
                <ul style={{ paddingLeft: '20px', margin: '0 0 10px 0' }}>
                  <li>Designing, editing, saving, and archiving custom cartridge specifications in native formats (<code>.wildcat</code>, <code>.wcs</code>).</li>
                  <li>Exporting engineering blueprints, reamer requisition forms, and toolmaker dimensional sheets for chamber reamer grinding by commercial toolrooms (JGS, PTG, Manson).</li>
                  <li>Calculating Simpson composite water capacity, volumetric expansion ratios, and powder charge estimates for internal ballistics modeling.</li>
                  <li>Simulating gyroscopic Miller twist stability and chamber setback configurations for lathe machining.</li>
                </ul>
              </div>

              <div>
                <h4 style={{ color: '#fff', fontSize: '13px', fontWeight: 700, margin: '0 0 6px 0' }}>
                  2. Restrictions & Confidential Source Code
                </h4>
                <p style={{ margin: '0 0 8px 0' }}>
                  The source code, mathematical routines, and internal data structures are the proprietary intellectual property of Daniel Cook.
                </p>
                <ul style={{ paddingLeft: '20px', margin: 0 }}>
                  <li>You may not decompile, reverse engineer, disassemble, or extract proprietary algorithms from the compiled binary applications.</li>
                  <li>You may not sell, rent, sub-license, or redistribute modified application packages.</li>
                  <li>Public binary redistribution is coordinated exclusively via <a href="https://armstrader.store/wildcat-studio" onClick={(e) => { e.preventDefault(); openExternalLink('https://armstrader.store/wildcat-studio'); }} style={{ color: 'var(--cad-cyan)', textDecoration: 'underline', cursor: 'pointer' }}>armstrader.store</a> and verified release channels.</li>
                </ul>
              </div>

              <div>
                <h4 style={{ color: '#fff', fontSize: '13px', fontWeight: 700, margin: '0 0 6px 0' }}>
                  3. Copyright & Ownership
                </h4>
                <p style={{ margin: 0 }}>
                  Copyright © 2026 Daniel Cook / Wildcat Studio. All rights reserved. All trademarks, registered chamber names, and brand mentions (e.g. SAAMI, CIP, JGS, PTG, Manson) belong to their respective holders and are referenced for toolmaker interoperability only.
                </p>
              </div>
            </>
          )}

          {activeTab === 'cleanroom' && (
            <>
              <div style={{
                background: 'rgba(59, 130, 246, 0.08)',
                border: '1px solid rgba(59, 130, 246, 0.25)',
                borderRadius: '6px',
                padding: '12px 14px',
                color: '#e2e8f0'
              }}>
                <strong style={{ color: '#60a5fa', display: 'block', marginBottom: '4px' }}>
                  Cleanroom Mathematical Formulation
                </strong>
                Every algorithmic calculation in Wildcat Studio is an independent, cleanroom implementation based on published peer-reviewed ballistic physics and open engineering standards.
              </div>

              <div>
                <h4 style={{ color: '#fff', fontSize: '13px', fontWeight: 700, margin: '0 0 6px 0' }}>
                  Numerical Volumetric Integrator (1,000 Slices)
                </h4>
                <p style={{ margin: '0 0 8px 0' }}>
                  Gross water capacity (grains H2O) is computed by treating the cartridge geometry as a solid of revolution along the longitudinal bore axis. The interior cavity is subdivided into 1,000 discrete volumetric slices evaluated via Simpson's composite numerical integration:
                </p>
                <div style={{
                  background: 'rgba(0, 0, 0, 0.4)',
                  border: '1px solid rgba(255, 255, 255, 0.08)',
                  borderRadius: '4px',
                  padding: '8px 12px',
                  fontFamily: 'var(--font-mono)',
                  fontSize: '11px',
                  color: 'var(--cad-cyan)'
                }}>
                  V = (π / 3) · Σ [ r_i² + r_i · r_(i+1) + r_(i+1)² ] · Δx
                </div>
                <p style={{ margin: '8px 0 0 0', fontSize: '11px', color: 'var(--text-muted)' }}>
                  Water capacity in grains is converted using standard distilled water density at 20°C (68°F) at 15.432 grains per cubic centimeter.
                </p>
              </div>

              <div>
                <h4 style={{ color: '#fff', fontSize: '13px', fontWeight: 700, margin: '0 0 6px 0' }}>
                  Miller Twist Rule & Gyroscopic Stability (Sg)
                </h4>
                <p style={{ margin: '0 0 8px 0' }}>
                  The Miller rule algorithm determines the gyroscopic stability factor (Sg) needed to stabilize a projectile of specified caliber, length, and weight:
                </p>
                <div style={{
                  background: 'rgba(0, 0, 0, 0.4)',
                  border: '1px solid rgba(255, 255, 255, 0.08)',
                  borderRadius: '4px',
                  padding: '8px 12px',
                  fontFamily: 'var(--font-mono)',
                  fontSize: '11px',
                  color: 'var(--cad-copper)'
                }}>
                  Sg = [ 30 · m ] / [ T² · d³ · l · (1 + l²) ] · (P / 29.92) · [ (460 + T_f) / 519 ]
                </div>
              </div>

              <div>
                <h4 style={{ color: '#fff', fontSize: '13px', fontWeight: 700, margin: '0 0 6px 0' }}>
                  Public Domain Standard Envelopes
                </h4>
                <p style={{ margin: 0 }}>
                  Baseline cartridge geometry and headspace datums for factory parent calibers conform to public voluntary engineering drawings published by SAAMI (USA) and C.I.P. (Europe).
                </p>
              </div>
            </>
          )}

          {activeTab === 'safety' && (
            <>
              <div style={{
                background: 'rgba(239, 68, 68, 0.1)',
                border: '1px solid rgba(239, 68, 68, 0.3)',
                borderRadius: '6px',
                padding: '14px 16px',
                color: '#fecaca'
              }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '6px' }}>
                  <AlertTriangle size={18} color="#ef4444" />
                  <strong style={{ color: '#ef4444', fontSize: '13px' }}>
                    CRITICAL TOOLROOM & RELOADING SAFETY WARNING
                  </strong>
                </div>
                <p style={{ margin: 0, fontSize: '11.5px', lineHeight: 1.6 }}>
                  Wildcat cartridge experimentation, chamber cutting, and fireforming involve substantial mechanical forces and high thermodynamic pressures. Calculated outputs are theoretical approximations and MUST NOT replace verified toolroom measurements and published manufacturer safety guidelines.
                </p>
              </div>

              <div>
                <h4 style={{ color: '#fff', fontSize: '13px', fontWeight: 700, margin: '0 0 6px 0' }}>
                  1. Headspace Gauge Verification
                </h4>
                <p style={{ margin: 0 }}>
                  Never fire a firearm chambered in a custom wildcat without first measuring and verifying chamber headspace using dedicated, calibrated precision GO and NO-GO gauges ground by accredited reamer manufacturers (such as JGS Precision Tooling, Pacific Tool & Gauge, or Manson Precision).
                </p>
              </div>

              <div>
                <h4 style={{ color: '#fff', fontSize: '13px', fontWeight: 700, margin: '0 0 6px 0' }}>
                  2. Powder Charge Development
                </h4>
                <p style={{ margin: 0 }}>
                  Estimated velocities and peak chamber pressures derived from expansion ratios and water capacity are mathematical guides. Powder lot burning rates vary significantly. When initiating handload development for any newly formed case, ALWAYS start with powder charges at least 10% below theoretical maximums, monitor primer appearance, case expansion, and bolt lift for early pressure signs.
                </p>
              </div>

              <div>
                <h4 style={{ color: '#fff', fontSize: '13px', fontWeight: 700, margin: '0 0 6px 0' }}>
                  3. Complete Disclaimer of Liability
                </h4>
                <p style={{ margin: 0 }}>
                  Under no circumstances shall the author, contributors, or affiliated distributors be held liable for direct, indirect, incidental, or consequential damages resulting from barrel bursting, chamber failure, firearm damage, personal injury, or loss of life associated with the assembly, machining, or firing of ammunition designed with this software.
                </p>
              </div>
            </>
          )}

          {activeTab === 'opensource' && (
            <>
              <p style={{ margin: 0 }}>
                Wildcat Studio is built upon the following world-class open source frameworks and libraries:
              </p>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                {[
                  {
                    name: 'Tauri Framework (Rust & WebKit)',
                    license: 'MIT / Apache-2.0',
                    desc: 'Native desktop application runtime, secure IPC bridge, and cross-platform native print integration.',
                    url: 'https://tauri.app'
                  },
                  {
                    name: 'React 18 & React-DOM',
                    license: 'MIT License',
                    desc: 'Declarative component architecture and high-frequency CAD drafting state management.',
                    url: 'https://react.dev'
                  },
                  {
                    name: 'Three.js Engine',
                    license: 'MIT License',
                    desc: 'WebGL-powered 3D lathe modeler, solid geometry revolution, and interactive lighting shaders.',
                    url: 'https://threejs.org'
                  },
                  {
                    name: 'Lucide Icons',
                    license: 'ISC License',
                    desc: 'Vector icon system providing clean, consistent CAD navigation and technical indicators.',
                    url: 'https://lucide.dev'
                  },
                  {
                    name: 'Vite & TypeScript',
                    license: 'MIT / Apache-2.0',
                    desc: 'Fast production module bundler and static type verification environment.',
                    url: 'https://vitejs.dev'
                  }
                ].map((item, idx) => (
                  <div 
                    key={idx}
                    style={{
                      background: 'rgba(255, 255, 255, 0.03)',
                      border: '1px solid rgba(255, 255, 255, 0.07)',
                      borderRadius: '6px',
                      padding: '10px 14px',
                      display: 'flex',
                      flexDirection: 'column',
                      gap: '3px'
                    }}
                  >
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                      <span style={{ color: '#fff', fontWeight: 700, fontSize: '12px' }}>
                        {item.name}
                      </span>
                      <span style={{
                        fontSize: '10px',
                        background: 'rgba(255, 255, 255, 0.06)',
                        padding: '1px 6px',
                        borderRadius: '3px',
                        color: 'var(--text-muted)'
                      }}>
                        {item.license}
                      </span>
                    </div>
                    <p style={{ margin: 0, fontSize: '11px', color: 'var(--text-secondary)' }}>
                      {item.desc}
                    </p>
                  </div>
                ))}
              </div>
            </>
          )}
        </div>

        {/* FOOTER */}
        <div style={{
          padding: '14px 24px',
          borderTop: '1px solid rgba(255, 255, 255, 0.08)',
          background: 'rgba(255, 255, 255, 0.02)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          flexShrink: 0
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <button
              onClick={handleCopy}
              style={{
                background: copied ? 'rgba(16, 185, 129, 0.15)' : 'rgba(255, 255, 255, 0.05)',
                border: `1px solid ${copied ? '#10b981' : 'rgba(255, 255, 255, 0.12)'}`,
                color: copied ? '#10b981' : 'var(--text-primary)',
                borderRadius: '5px',
                padding: '6px 12px',
                fontSize: '11.5px',
                fontWeight: 600,
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: '6px',
                transition: 'all 0.15s'
              }}
            >
              {copied ? <Check size={14} color="#10b981" /> : <Copy size={14} />}
              <span>{copied ? 'Copied Full License' : 'Copy Full License Text'}</span>
            </button>

            <button
              onClick={() => openExternalLink('https://armstrader.store/wildcat-studio')}
              style={{
                background: 'transparent',
                border: 'none',
                color: 'var(--cad-cyan)',
                fontSize: '11.5px',
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: '5px',
                padding: '6px 8px'
              }}
            >
              <span>armstrader.store/wildcat-studio</span>
              <ExternalLink size={12} opacity={0.7} />
            </button>
          </div>

          <button
            onClick={onClose}
            style={{
              background: 'var(--cad-cyan)',
              color: '#0a0e17',
              border: 'none',
              borderRadius: '5px',
              padding: '7px 20px',
              fontSize: '12px',
              fontWeight: 700,
              cursor: 'pointer',
              transition: 'all 0.15s'
            }}
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
