import React, { useState } from 'react';
import { CartridgeSpec } from '../types/cartridge';
import { calculateMillerStability } from '../utils/volumetrics';
import { getBulletsForCaliber, BULLET_OPTIONS } from '../data/bullets';
import { X, Compass, Info, Check, Copy, Printer, Download } from 'lucide-react';
import { openStandalonePrintWindow, saveExportFile } from '../utils/fileExport';

interface TwistStabilityModalProps {
  isOpen: boolean;
  onClose: () => void;
  cartridge: CartridgeSpec;
  isMetric: boolean;
}

export const TwistStabilityModal: React.FC<TwistStabilityModalProps> = ({
  isOpen,
  onClose,
  cartridge,
  isMetric,
}) => {
  // Local state for interactive tuning
  const [bulletWeight, setBulletWeight] = useState<number>(cartridge.bullet_weight_grains || 150);
  const [bulletLength, setBulletLength] = useState<number>(
    cartridge.bullet_length > 0 ? cartridge.bullet_length : Math.round(cartridge.bullet_diameter * 3.4 * 100) / 100
  );
  const [twistRate, setTwistRate] = useState<number>(10.0);
  const [velocity, setVelocity] = useState<number>(2800);
  const [copied, setCopied] = useState<boolean>(false);

  if (!isOpen) return null;

  // Clone cartridge with current interactive values
  const currentSpec: CartridgeSpec = {
    ...cartridge,
    bullet_weight_grains: bulletWeight,
    bullet_length: bulletLength,
  };

  const result = calculateMillerStability(currentSpec, twistRate, velocity);

  const statusColors: Record<string, string> = {
    unstable: '#ef4444',
    marginal: '#f59e0b',
    stable: '#10b981',
    over_stabilized: '#3b82f6',
  };

  const statusBg: Record<string, string> = {
    unstable: 'rgba(239, 68, 68, 0.12)',
    marginal: 'rgba(245, 158, 11, 0.12)',
    stable: 'rgba(16, 185, 129, 0.12)',
    over_stabilized: 'rgba(59, 130, 246, 0.12)',
  };

  const statusLabels: Record<string, string> = {
    unstable: 'UNSTABLE (Sg < 1.0)',
    marginal: 'MARGINAL (1.0 ≤ Sg < 1.3)',
    stable: 'OPTIMALLY STABLE (1.3 ≤ Sg ≤ 2.0)',
    over_stabilized: 'OVER-STABILIZED (Sg > 2.0)',
  };

  const generateReportText = () => {
    return `================================================================================
           MILLER GYROSCOPIC STABILITY ANALYSIS & SPECIFICATION
================================================================================
Cartridge Designation : ${cartridge.name}
Standard              : ${cartridge.standard.toUpperCase()}
Generated Date        : ${new Date().toLocaleDateString()}
Generated By          : Wildcat Studio Engineering CAD Suite

[PROJECTILE & BALLISTIC PARAMETERS]
Bore / Bullet Diameter: ${cartridge.bullet_diameter.toFixed(3)}" (${(cartridge.bullet_diameter * 25.4).toFixed(2)} mm)
Bullet Mass           : ${bulletWeight} gr (${(bulletWeight * 0.0647989).toFixed(2)} g)
Bullet Length         : ${bulletLength.toFixed(3)}" (${(bulletLength * 25.4).toFixed(2)} mm)
Muzzle Velocity       : ${velocity} fps (${(velocity * 0.3048).toFixed(0)} m/s)
Simulated Twist Rate  : 1:${twistRate.toFixed(1)}"

[GYROSCOPIC STABILITY RESULTS]
Stability Factor (Sg) : ${result.sg.toFixed(2)}
Flight Dynamic State  : ${result.status.replace('_', ' ').toUpperCase()}
Benchmark Match Twist : 1:${result.optimal_twist_inches.toFixed(1)}" (for ideal Sg = 1.50)
Status Diagnostic     : ${result.description}

[BARREL TWIST SPECTRUM SENSITIVITY]
${[7.0, 8.0, 9.0, 10.0, 12.0]
  .map((t) => {
    const sub = calculateMillerStability(currentSpec, t, velocity);
    const activeFlag = Math.abs(twistRate - t) < 0.05 ? ' <-- ACTIVE' : '';
    return `  1:${t.toFixed(1).padEnd(4)}" Twist -> Sg = ${sub.sg.toFixed(2).padEnd(5)} (${sub.status.replace('_', ' ').toUpperCase()})${activeFlag}`;
  })
  .join('\n')}

[PHYSICS & FORMULATION NOTES]
Calculated using the Don Miller modified gyroscopic stability equation:
Sg = [30 * m] / [t^2 * d^3 * l * (1 + l^2)] * sqrt(v / 2800)
Corrected for velocity scaling at sea-level standard temperature and pressure (STP).
Target precision benchmark: 1.30 <= Sg <= 2.00 for match accuracy.
================================================================================`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateReportText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadReport = async () => {
    const text = generateReportText();
    const safeName = cartridge.name.toLowerCase().replace(/[^a-z0-9]+/g, '_');
    await saveExportFile({
      defaultFileName: `${safeName}_stability_report.txt`,
      filters: [{ name: 'Text Report', extensions: ['txt'] }],
      content: text,
      mimeType: 'text/plain',
      title: 'Export Gyroscopic Stability Report',
    });
  };

  const handlePrintReport = async () => {
    const printHtml = `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>${cartridge.name} - Gyroscopic Twist Stability Sheet</title>
    <style>
      @page { size: letter portrait; margin: 0.5in; }
      body {
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
        color: #0f172a;
        background: #ffffff;
        margin: 0;
        padding: 16px;
        line-height: 1.5;
        -webkit-print-color-adjust: exact;
        print-color-adjust: exact;
      }
      .header {
        border-bottom: 2px solid #0f172a;
        padding-bottom: 10px;
        margin-bottom: 16px;
        display: flex;
        justify-content: space-between;
        align-items: flex-end;
      }
      .header-title { font-size: 20px; font-weight: 800; color: #0f172a; margin: 0; }
      .header-sub { font-size: 11px; color: #64748b; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; }
      .header-date { font-size: 11px; font-family: monospace; color: #475569; text-align: right; }
      .summary-card {
        border: 1.5px solid #cbd5e1;
        border-radius: 6px;
        padding: 16px;
        background: #f8fafc;
        margin-bottom: 18px;
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 16px;
      }
      .metric-box { border-left: 3px solid #0284c7; padding-left: 10px; }
      .metric-label { font-size: 10px; font-weight: 700; text-transform: uppercase; color: #64748b; }
      .metric-value { font-size: 22px; font-weight: 800; font-family: monospace; color: #0f172a; margin: 2px 0; }
      .metric-desc { font-size: 11px; color: #334155; }
      table { width: 100%; border-collapse: collapse; margin-top: 14px; font-size: 11px; }
      th, td { border: 1px solid #cbd5e1; padding: 8px 10px; text-align: left; }
      th { background: #f1f5f9; font-weight: bold; color: #334155; }
      tr.active-twist { background: #f0fdf4; font-weight: bold; border: 2px solid #16a34a; }
      .section-title { font-size: 13px; font-weight: 800; color: #0f172a; margin: 18px 0 6px 0; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }
      .formula-box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 12px; font-size: 11px; color: #475569; margin-top: 20px; line-height: 1.6; }
      .footer { margin-top: 24px; border-top: 1px solid #cbd5e1; padding-top: 8px; font-size: 10px; color: #94a3b8; display: flex; justify-content: space-between; }
    </style>
  </head>
  <body>
    <div class="header">
      <div>
        <div class="header-sub">Wildcat Studio Engineering CAD Telemetry</div>
        <h1 class="header-title">${cartridge.name} &bull; Gyroscopic Twist Stability Sheet</h1>
      </div>
      <div class="header-date">
        DATE: ${new Date().toLocaleDateString()}<br/>
        STANDARD: ${cartridge.standard.toUpperCase()}
      </div>
    </div>

    <div class="summary-card">
      <div class="metric-box" style="border-left-color: ${statusColors[result.status] || '#0284c7'};">
        <div class="metric-label">Gyroscopic Stability Factor (Sg)</div>
        <div class="metric-value" style="color: ${statusColors[result.status] || '#0f172a'};">${result.sg.toFixed(2)}</div>
        <div class="metric-desc"><strong>${result.status.replace('_', ' ').toUpperCase()}</strong>: ${result.description}</div>
      </div>
      <div class="metric-box" style="border-left-color: #0284c7;">
        <div class="metric-label">Recommended Optimal Match Twist</div>
        <div class="metric-value">1 : ${result.optimal_twist_inches.toFixed(1)}"</div>
        <div class="metric-desc">Calculated barrel rifling rate to achieve benchmark Sg = 1.50 stability factor</div>
      </div>
    </div>

    <div class="section-title">Ballistic & Projectile Parameters</div>
    <table>
      <thead>
        <tr>
          <th>Caliber / Bore Dia</th>
          <th>Bullet Mass</th>
          <th>Bullet Length</th>
          <th>Muzzle Velocity</th>
          <th>Simulated Twist</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>.${Math.round(cartridge.bullet_diameter * 1000)} (${cartridge.bullet_diameter.toFixed(3)}" / ${(cartridge.bullet_diameter * 25.4).toFixed(2)} mm)</td>
          <td>${bulletWeight} grains (${(bulletWeight * 0.0647989).toFixed(2)} g)</td>
          <td>${bulletLength.toFixed(3)}" (${(bulletLength * 25.4).toFixed(2)} mm)</td>
          <td>${velocity} fps (${(velocity * 0.3048).toFixed(0)} m/s)</td>
          <td><strong>1 : ${twistRate.toFixed(1)}"</strong></td>
        </tr>
      </tbody>
    </table>

    <div class="section-title">Barrel Twist Sensitivity Spectrum (5 Standard Rifling Rates)</div>
    <table>
      <thead>
        <tr>
          <th>Rifling Twist Rate</th>
          <th>Stability Factor (Sg)</th>
          <th>Flight Dynamic State</th>
          <th>Aerodynamic Drag Impact</th>
          <th>Application Suitability</th>
        </tr>
      </thead>
      <tbody>
        ${[7.0, 8.0, 9.0, 10.0, 12.0]
          .map((t) => {
            const sub = calculateMillerStability(currentSpec, t, velocity);
            const isActive = Math.abs(twistRate - t) < 0.05;
            return `
            <tr class="${isActive ? 'active-twist' : ''}">
              <td><strong>1 : ${t.toFixed(1)}"</strong> ${isActive ? ' &bull; ACTIVE' : ''}</td>
              <td><span style="font-family: monospace; font-weight: bold; color: ${statusColors[sub.status]};">${sub.sg.toFixed(2)}</span></td>
              <td style="text-transform: capitalize; color: ${statusColors[sub.status]};"><strong>${sub.status.replace('_', ' ')}</strong></td>
              <td>${sub.sg < 1.0 ? 'Severe tumbling / Keyholing risk' : sub.sg < 1.3 ? 'Marginal yawing, reduced BC efficiency' : sub.sg <= 2.0 ? 'Optimal BC retention, pinpoint dispersion' : 'Slight spin drift / Core jacket stress'}</td>
              <td>${sub.sg >= 1.3 && sub.sg <= 2.0 ? 'Match / Competition / Tactical' : sub.sg > 2.0 ? 'Varmint / High-RPM Hunting' : 'Not recommended for this projectile'}</td>
            </tr>
          `;
          })
          .join('')}
      </tbody>
    </table>

    <div class="formula-box">
      <strong>Engineering Physics Footnote:</strong> Don Miller modified stability formulation:
      <code>Sg = [30 * m] / [t² * d³ * l * (1 + l²)] * √(v / 2800)</code> where <em>m</em> = projectile grains, <em>t</em> = twist in calibers, <em>d</em> = diameter (in), <em>l</em> = length in calibers, and <em>v</em> = velocity (fps). Corrected for standard sea-level STP conditions (59&deg;F / 15&deg;C, 29.92 inHg). Values of 1.30 &le; Sg &le; 2.00 provide optimum precision without excessive spin drift.
    </div>

    <div class="footer">
      <span>Wildcat Studio CAD Suite &bull; Precision Ballistics Engine</span>
      <span>Document ID: STAB-${Date.now().toString(36).toUpperCase()} &bull; ISO/ANSI Ballistic Spec</span>
    </div>
  </body>
</html>`;
    await openStandalonePrintWindow(printHtml, `${cartridge.name} Twist Stability Sheet`);
  };

  // Stability Gauge needle position: clamp Sg between 0.5 and 2.5 mapped to 0% to 100%
  const needlePct = Math.max(0, Math.min(100, ((result.sg - 0.5) / 2.0) * 100));

  return (
    <div
      style={{
        position: 'fixed',
        inset: 0,
        zIndex: 100,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(5, 8, 15, 0.82)',
        WebkitBackdropFilter: 'blur(8px)',
        backdropFilter: 'blur(8px)',
      }}
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div
        style={{
          background: 'var(--bg-secondary)',
          border: '1px solid var(--border-color)',
          borderRadius: '12px',
          width: '780px',
          maxWidth: '95vw',
          maxHeight: '90vh',
          display: 'flex',
          flexDirection: 'column',
          boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.75)',
          overflow: 'hidden',
          position: 'relative',
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div
          style={{
            padding: '14px 18px',
            borderBottom: '1px solid var(--border-color)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            background: 'var(--bg-tertiary)',
            flexShrink: 0,
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <div
              style={{
                width: '32px',
                height: '32px',
                borderRadius: '6px',
                background: 'rgba(240, 136, 62, 0.15)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                color: 'var(--cad-copper)',
              }}
            >
              <Compass size={18} />
            </div>
            <div>
              <h2 style={{ fontSize: '15px', fontWeight: 600, color: 'var(--text-primary)', margin: 0 }}>
                Miller Twist Rule & Gyroscopic Stability (Sg)
              </h2>
              <p style={{ fontSize: '11px', color: 'var(--text-muted)', margin: '2px 0 0 0' }}>
                Don Miller aerodynamic stability modeling for {cartridge.name}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            style={{
              background: 'transparent',
              border: 'none',
              color: 'var(--text-muted)',
              cursor: 'pointer',
              padding: '6px',
              borderRadius: '6px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
            }}
          >
            <X size={18} />
          </button>
        </div>

        {/* Body */}
        <div
          style={{
            flex: 1,
            minHeight: 0,
            padding: '14px 18px',
            overflowY: 'auto',
            display: 'flex',
            flexDirection: 'column',
            gap: '12px',
          }}
        >
          {/* Main Sg Status Hero & Graphical Spectrum Card */}
          <div
            style={{
              padding: '14px 16px',
              borderRadius: '10px',
              background: statusBg[result.status],
              border: `1.5px solid ${statusColors[result.status]}`,
              display: 'flex',
              flexDirection: 'column',
              gap: '12px',
            }}
          >
            {/* Top row: Metrics */}
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '16px' }}>
              <div>
                <span
                  style={{
                    fontSize: '10.5px',
                    fontWeight: 700,
                    color: statusColors[result.status],
                    letterSpacing: '0.5px',
                    textTransform: 'uppercase',
                    background: 'rgba(0, 0, 0, 0.25)',
                    padding: '2px 8px',
                    borderRadius: '4px',
                    border: `1px solid ${statusColors[result.status]}40`,
                    display: 'inline-block',
                  }}
                >
                  {statusLabels[result.status]}
                </span>
                <div style={{ display: 'flex', alignItems: 'baseline', gap: '10px', margin: '4px 0 2px 0' }}>
                  <span style={{ fontSize: '28px', fontWeight: 800, color: '#fff', fontFamily: 'var(--font-mono)', lineHeight: 1 }}>
                    Sg = {result.sg.toFixed(2)}
                  </span>
                  <span style={{ fontSize: '11.5px', color: '#cbd5e1' }}>
                    {result.description}
                  </span>
                </div>
              </div>

              <div
                style={{
                  textAlign: 'right',
                  borderLeft: '1px solid rgba(255, 255, 255, 0.12)',
                  paddingLeft: '16px',
                  flexShrink: 0,
                }}
              >
                <span style={{ fontSize: '10px', color: 'var(--text-muted)', display: 'block', fontWeight: 600 }}>
                  OPTIMAL MATCH TWIST (Sg=1.5)
                </span>
                <span style={{ fontSize: '20px', fontWeight: 700, color: '#34d399', fontFamily: 'var(--font-mono)' }}>
                  1 : {result.optimal_twist_inches.toFixed(1)}"
                </span>
                <span style={{ fontSize: '10px', color: 'var(--text-muted)', display: 'block', marginTop: '1px' }}>
                  {isMetric ? `1 in ${(result.optimal_twist_inches * 25.4).toFixed(0)} mm` : 'calibers per turn'}
                </span>
              </div>
            </div>

            {/* Bottom row: Integrated Stability Spectrum Bar */}
            <div style={{ background: 'rgba(10, 15, 26, 0.5)', padding: '8px 12px 6px 12px', borderRadius: '6px', border: '1px solid rgba(255, 255, 255, 0.08)' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '10px', color: 'var(--text-muted)', marginBottom: '4px' }}>
                <span>0.5 (Tumble)</span>
                <span style={{ color: '#f59e0b' }}>1.0 (Marginal)</span>
                <span style={{ color: '#10b981', fontWeight: 700 }}>1.5 (Match Ideal)</span>
                <span style={{ color: '#3b82f6' }}>2.0 (Overspin)</span>
                <span>2.5+</span>
              </div>

              <div style={{ position: 'relative', height: '10px', borderRadius: '5px', overflow: 'hidden', display: 'flex' }}>
                <div style={{ width: '25%', background: '#ef4444' }} title="Unstable (<1.0)" />
                <div style={{ width: '15%', background: '#f59e0b' }} title="Marginal (1.0 - 1.3)" />
                <div style={{ width: '35%', background: '#10b981' }} title="Optimal (1.3 - 2.0)" />
                <div style={{ width: '25%', background: '#3b82f6' }} title="Over-Stabilized (>2.0)" />
              </div>

              {/* Needle pointer */}
              <div style={{ position: 'relative', height: '14px', marginTop: '3px' }}>
                <div
                  style={{
                    position: 'absolute',
                    left: `${needlePct}%`,
                    transform: 'translateX(-50%)',
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'center',
                    transition: 'left 0.2s ease',
                  }}
                >
                  <div style={{ width: 0, height: 0, borderLeft: '4px solid transparent', borderRight: '4px solid transparent', borderBottom: '5px solid #fff' }} />
                  <span style={{ fontSize: '9.5px', fontWeight: 700, color: '#fff', fontFamily: 'var(--font-mono)' }}>
                    {result.sg.toFixed(2)}
                  </span>
                </div>
              </div>
            </div>
          </div>

          {/* Interactive Ballistic Tuning Controls with Integrated Preset Selector */}
          <div
            style={{
              padding: '12px 16px',
              background: 'var(--bg-tertiary)',
              borderRadius: '8px',
              border: '1px solid var(--border-color)',
              display: 'flex',
              flexDirection: 'column',
              gap: '10px',
            }}
          >
            {/* Header row: Factory Bullet Preset Picker */}
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                gap: '12px',
                paddingBottom: '8px',
                borderBottom: '1px solid var(--border-color)',
              }}
            >
              <div>
                <span style={{ fontSize: '11px', fontWeight: 700, color: 'var(--cad-cyan)', letterSpacing: '0.4px' }}>
                  FACTORY BULLET PRESET ({cartridge.bullet_diameter.toFixed(3)}" Caliber)
                </span>
                <span style={{ fontSize: '10px', color: 'var(--text-muted)', marginLeft: '8px' }}>
                  Auto-populate mass & length
                </span>
              </div>
              {(() => {
                const activeBullet = BULLET_OPTIONS.find(b => 
                  Math.abs(b.caliber_inches - cartridge.bullet_diameter) < 0.003 && 
                  b.weight_grains === bulletWeight &&
                  Math.abs(b.length_inches - bulletLength) < 0.02
                );

                return (
                  <select
                    value={activeBullet ? activeBullet.id : ""}
                    onChange={(e) => {
                      const b = BULLET_OPTIONS.find(item => item.id === e.target.value);
                      if (b) {
                        setBulletWeight(b.weight_grains);
                        setBulletLength(b.length_inches);
                      }
                    }}
                    style={{
                      background: 'var(--bg-secondary)',
                      color: '#fff',
                      border: `1px solid ${activeBullet ? 'rgba(0, 210, 255, 0.6)' : 'rgba(0, 210, 255, 0.35)'}`,
                      borderRadius: '6px',
                      padding: '4px 8px',
                      fontSize: '11px',
                      outline: 'none',
                      cursor: 'pointer',
                      minWidth: '240px',
                      maxWidth: '340px',
                    }}
                  >
                    <option value="" disabled>Select factory bullet model...</option>
                    <optgroup label={`Matches for ${cartridge.bullet_diameter.toFixed(3)}" Caliber`}>
                      {getBulletsForCaliber(cartridge.bullet_diameter, 0.008).map((b) => (
                        <option key={b.id} value={b.id}>
                          {b.name} — {b.weight_grains} gr (L: {b.length_inches}", BC: {b.g1_bc})
                        </option>
                      ))}
                    </optgroup>
                    <optgroup label="Other Calibers">
                      {BULLET_OPTIONS.filter(b => Math.abs(b.caliber_inches - cartridge.bullet_diameter) > 0.008).map((b) => (
                        <option key={b.id} value={b.id}>
                          .{b.caliber_inches.toString().split('.')[1]} — {b.name} ({b.weight_grains} gr)
                        </option>
                      ))}
                    </optgroup>
                  </select>
                );
              })()}
            </div>

            {/* Ballistic Tuning Controls Grid */}
            <div
              style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(2, 1fr)',
                gap: '10px 16px',
              }}
            >
              {/* Twist Rate Slider */}
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '3px' }}>
                  <label style={{ fontSize: '11.5px', fontWeight: 600, color: '#e2e8f0' }}>Barrel Twist Rate</label>
                  <span style={{ fontSize: '11.5px', fontWeight: 700, color: 'var(--cad-cyan)', fontFamily: 'var(--font-mono)' }}>
                    1 : {twistRate.toFixed(1)}"
                  </span>
                </div>
                <input
                  type="range"
                  min="6.0"
                  max="16.0"
                  step="0.25"
                  value={twistRate}
                  onChange={(e) => setTwistRate(parseFloat(e.target.value))}
                  style={{ width: '100%', cursor: 'pointer', accentColor: 'var(--cad-cyan)' }}
                />
              </div>

              {/* Muzzle Velocity Slider */}
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '3px' }}>
                  <label style={{ fontSize: '11.5px', fontWeight: 600, color: '#e2e8f0' }}>Muzzle Velocity</label>
                  <span style={{ fontSize: '11.5px', fontWeight: 700, color: '#34d399', fontFamily: 'var(--font-mono)' }}>
                    {velocity} fps {isMetric ? `(${(velocity * 0.3048).toFixed(0)} m/s)` : ''}
                  </span>
                </div>
                <input
                  type="range"
                  min="1000"
                  max="4200"
                  step="25"
                  value={velocity}
                  onChange={(e) => setVelocity(parseInt(e.target.value))}
                  style={{ width: '100%', cursor: 'pointer', accentColor: '#34d399' }}
                />
              </div>

              {/* Bullet Weight */}
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '3px' }}>
                  <label style={{ fontSize: '11.5px', fontWeight: 600, color: '#e2e8f0' }}>Bullet Mass (Grains)</label>
                  <span style={{ fontSize: '11.5px', fontWeight: 700, color: 'var(--cad-copper)', fontFamily: 'var(--font-mono)' }}>
                    {bulletWeight} gr
                  </span>
                </div>
                <input
                  type="number"
                  min="15"
                  max="1000"
                  value={bulletWeight}
                  onChange={(e) => setBulletWeight(Math.max(1, parseFloat(e.target.value) || 0))}
                  style={{
                    width: '100%',
                    background: 'var(--bg-secondary)',
                    border: '1px solid var(--border-color)',
                    borderRadius: '6px',
                    color: '#fff',
                    padding: '5px 8px',
                    fontSize: '11.5px',
                    fontFamily: 'var(--font-mono)',
                    boxSizing: 'border-box',
                  }}
                />
              </div>

              {/* Bullet Length */}
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '3px' }}>
                  <label style={{ fontSize: '11.5px', fontWeight: 600, color: '#e2e8f0' }}>Total Bullet Length</label>
                  <span style={{ fontSize: '11.5px', fontWeight: 700, color: '#e5be59', fontFamily: 'var(--font-mono)' }}>
                    {bulletLength.toFixed(3)}" {isMetric ? `(${(bulletLength * 25.4).toFixed(1)} mm)` : ''}
                  </span>
                </div>
                <input
                  type="number"
                  step="0.010"
                  min="0.100"
                  max="4.000"
                  value={bulletLength}
                  onChange={(e) => setBulletLength(Math.max(0.1, parseFloat(e.target.value) || 0.1))}
                  style={{
                    width: '100%',
                    background: 'var(--bg-secondary)',
                    border: '1px solid var(--border-color)',
                    borderRadius: '6px',
                    color: '#fff',
                    padding: '5px 8px',
                    fontSize: '11.5px',
                    fontFamily: 'var(--font-mono)',
                    boxSizing: 'border-box',
                  }}
                />
              </div>
            </div>
          </div>

          {/* Miller Twist Reference Matrix */}
          <div style={{ background: 'rgba(15, 20, 31, 0.5)', borderRadius: '8px', border: '1px solid var(--border-color)', overflow: 'hidden' }}>
            <div
              style={{
                padding: '8px 12px',
                background: 'var(--bg-tertiary)',
                borderBottom: '1px solid var(--border-color)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
              }}
            >
              <div>
                <span style={{ fontSize: '11px', fontWeight: 700, color: '#e2e8f0', letterSpacing: '0.4px' }}>
                  BARREL TWIST COMPARATIVE SPECTRUM
                </span>
                <span style={{ fontSize: '10px', color: 'var(--text-muted)', marginLeft: '8px' }}>
                  (Click any rate below to simulate)
                </span>
              </div>
              <span
                style={{
                  fontSize: '10px',
                  color: 'var(--cad-cyan)',
                  fontWeight: 700,
                  fontFamily: 'var(--font-mono)',
                  background: 'rgba(0, 210, 255, 0.12)',
                  padding: '2px 7px',
                  borderRadius: '3px',
                  border: '1px solid rgba(0, 210, 255, 0.3)',
                }}
              >
                Active: 1:{twistRate.toFixed(1)}"
              </span>
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: '1px', background: 'var(--border-color)' }}>
              {[7.0, 8.0, 9.0, 10.0, 12.0].map((testTwist) => {
                const subRes = calculateMillerStability(currentSpec, testTwist, velocity);
                const isSelected = Math.abs(twistRate - testTwist) < 0.05;
                return (
                  <div
                    key={testTwist}
                    onClick={() => setTwistRate(testTwist)}
                    title={`Click to set barrel rifling to 1:${testTwist}"`}
                    style={{
                      background: isSelected ? 'rgba(0, 210, 255, 0.18)' : 'var(--bg-secondary)',
                      padding: '8px 6px',
                      textAlign: 'center',
                      cursor: 'pointer',
                      transition: 'all 0.15s ease',
                      border: isSelected ? '1px solid var(--cad-cyan)' : '1px solid transparent',
                      position: 'relative',
                    }}
                  >
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '4px' }}>
                      <span style={{ fontSize: '11px', fontWeight: 700, color: isSelected ? '#fff' : '#cbd5e1' }}>
                        1 : {testTwist}"
                      </span>
                      {isSelected && (
                        <span style={{ fontSize: '8px', fontWeight: 700, color: 'var(--cad-cyan)', textTransform: 'uppercase' }}>
                          ●
                        </span>
                      )}
                    </div>
                    <div style={{ fontSize: '13px', fontWeight: 700, color: statusColors[subRes.status], fontFamily: 'var(--font-mono)', margin: '2px 0' }}>
                      {subRes.sg.toFixed(2)}
                    </div>
                    <div style={{ fontSize: '9px', color: statusColors[subRes.status], textTransform: 'capitalize', fontWeight: 600 }}>
                      {subRes.status.replace('_', ' ')}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>

        {/* Footer */}
        <div
          style={{
            padding: '14px 20px',
            borderTop: '1px solid var(--border-color)',
            background: 'var(--bg-tertiary)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: '14px',
            flexShrink: 0,
          }}
        >
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
              fontSize: '11px',
              color: 'var(--text-muted)',
              minWidth: 0,
              flex: 1,
            }}
          >
            <Info size={13} style={{ flexShrink: 0 }} />
            <span
              style={{
                overflow: 'hidden',
                textOverflow: 'ellipsis',
                whiteSpace: 'nowrap',
              }}
              title="Don Miller formula corrected for velocity factor √(v / 2800) at sea level STP"
            >
              Don Miller formula corrected for velocity factor √(v / 2800) at sea level STP
            </span>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexShrink: 0 }}>
            <button
              onClick={handlePrintReport}
              style={{
                background: 'var(--cad-cyan)',
                border: 'none',
                borderRadius: '6px',
                color: '#090d14',
                padding: '6px 13px',
                fontSize: '11.5px',
                fontWeight: 700,
                display: 'flex',
                alignItems: 'center',
                gap: '6px',
                cursor: 'pointer',
              }}
              title="Print high-resolution engineering stability report sheet"
            >
              <Printer size={13} />
              <span>Print Stability Sheet</span>
            </button>

            <button
              onClick={handleDownloadReport}
              style={{
                background: 'rgba(255, 255, 255, 0.06)',
                border: '1px solid var(--border-color)',
                borderRadius: '6px',
                color: '#e2e8f0',
                padding: '6px 12px',
                fontSize: '11.5px',
                fontWeight: 600,
                display: 'flex',
                alignItems: 'center',
                gap: '6px',
                cursor: 'pointer',
              }}
              title="Save report to local text file (.txt)"
            >
              <Download size={13} />
              <span>Download (.txt)</span>
            </button>

            <button
              onClick={handleCopy}
              style={{
                background: 'rgba(255, 255, 255, 0.04)',
                border: '1px solid var(--border-color)',
                borderRadius: '6px',
                color: 'var(--text-secondary)',
                padding: '6px 10px',
                fontSize: '11.5px',
                fontWeight: 600,
                display: 'flex',
                alignItems: 'center',
                gap: '5px',
                cursor: 'pointer',
              }}
              title="Copy formatted stability report to clipboard"
            >
              {copied ? <Check size={13} color="#10b981" /> : <Copy size={13} />}
              <span>{copied ? 'Copied' : 'Copy'}</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
